server:
    port: 8080
spring:
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 운영서버
#    url: jdbc:mysql://company-source.com:8306/cs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # 개발서버
    url: jdbc:mysql://k8b107.p.ssafy.io:8306/cs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: comso
    password: B107
    hikari:
      leak-detection-threshold: 2000
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      # 운영서버
#      host: company-source.com
      # 개발서버
      host : k8b107.p.ssafy.io
      authentication-database: admin
      username: comso
      password: B107
      database: company-source
      port: 9000

#    mongodb: # 테스트
#      host: k8b107.p.ssafy.io
#      authentication-database: admin
#      username: comso
#      password: B107
#      database: cs-test
#      port: 9000
#        mongodb://comso:B107@company-source.com:9000/?authMechanism=DEFAULT
  redis:
    # 운영서버
#    host: company-source.com
    # 개발서버
    host: k8b107.p.ssafy.io
    port: 8379
    password: "B107"

#jwt:
#  secret: 'myprojectsecret'